### ISSUE TITLE
About calculate dist score

### ISSUE THREAD

**Issue by huanghonggit** [andreamad8/PPCM#3]
Why calculate the dist2 of each sentence? And when calculating dist2, for example, dist2=16/17≈0.94; when outputting, it outputs 1-dist2?
![image](https://user-images.githubusercontent.com/49581245/114377291-0fb97700-9bb9-11eb-9faf-ac3b63449d56.png)

**Comment by andreamad8** [comment]
Hi, 

I think I did that cause I was using it to rank different hypothesis. 

Andrea

**Comment by huanghonggit** [comment]
Thank you for your reply；I don't understand why the calculation of dist2 is through 1-score;  I know the method of calculating dist like this: 
![image](https://user-images.githubusercontent.com/49581245/114586110-e4b54d00-9cb6-11eb-8e47-039cb1c17658.png)
And the dist score of the result should be wrong？
![image](https://user-images.githubusercontent.com/49581245/114586333-20501700-9cb7-11eb-8718-0a971101dfe5.png)
![image](https://user-images.githubusercontent.com/49581245/114586403-3362e700-9cb7-11eb-8db1-db8ee78bdc0e.png)

**Comment by andreamad8** [comment]
I don't fully get your question. 
I used existing code for the dist score calculation.

**Comment by huanghonggit** [comment]
I'm sorry, maybe I didn't say it clearly... My problem is that I don't understand why you calculate the dist score, why the result is displayed as the value of 1-dist2

**Comment by andreamad8** [comment]
yah, I compute the dist score for reporting the results in the paper, but then when I was running the experiments I was checking only dist-2. Also because I didn't want to check too many numbers . :)
