### ISSUE TITLE
There are some missing arguments (e.g., "entailment", "BCE", and "bag_of_words")

### ISSUE THREAD

**Issue by passing2961** [andreamad8/PPCM#4]
Hi,

When I ran the PPLM, I found there are some missing arguments (e.g., "entailment," "BCE," and "bag_of_words").

So, I added few lines as below, and then solved the issue. Would it be okay to add the code like this?

```python
parser.add_argument("--entailment", type=bool, default=False)
parser.add_argument("--BCE", type=bool, default=False)
parser.add_argument("--bag_of_words", type=str, default=None)
```

**Comment by andreamad8** [comment]
Hi, 

oh, I forget to clean that part of the code. Yes, that would be right, those were some flags I used for other experiments. 

I will push a quick fix. 

Andrea

**Comment by passing2961** [comment]
Oh, I see.

Thank you for the kind reply :)

Young-Jun Lee

**Comment by andreamad8** [comment]
good catch, I just added those, in case someone wanna use bag_of_words or BCE loss for the discriminator. 

Best

Andrea
