### ISSUE TITLE
Module "resp_ppl" is missing

### ISSUE THREAD

**Issue by passing2961** [andreamad8/PPCM#5]
Hi, 

When I trained the residual adapter part, I encountered one import module error from `train_supervised_adapter.py`, which is shown below:

```python
with jsonlines.open(f) as reader: 
        for i, obj in enumerate(reader):
            text = " ".join(tokenize.sent_tokenize(obj["hyp"]["PPLM"][0][-1])[:2])
            score = resp_ppl(text)
            if score>700:
                continue
            response.append(obj['conversation']['conversation']+[text])
```

In the above code, I couldn't find the function of `resp_ppl,` so I removed that part for training the adapter module. Is it okay to proceed like this?

p.s. Sorry for ask again.

Thank you,
Young-Jun Lee

**Comment by andreamad8** [comment]
Hi, 

yes, it was renamed as "get_ppl". Really thank you for spotting this mistakes 😊👍🏻

Let me know if you find more. 

I push a quick fix. 

Andrea
