### ISSUE TITLE
I have a question about the residual adapter

### ISSUE THREAD

**Issue by passing2961** [andreamad8/PPCM#6]
Hi, 

After reading your paper PPCM, I have a question related to the Plug-and-Play Adapters. As mentioned in your paper, we have to generate style-specific datasets using PPLM with some trained discriminators. Then, we only optimize the residual adapter parameters to steer the output of the original LM distribution (we don't need to optimize the LM parameter meaning that fixed parameters). At the decoding time, we use these trained models (not requiring a fixed number of iterations). This is what I understand of your paper; I don't know it is right. I am not sure.

And I tried to run your code. When I trained the residual adapter, I found a part that I didn't understand. In the `train_supervised_adpater.py` file, there are 8 task ids (shown in the below figure).

```python
TASK_MAP = {"very_negative":0, "very_positive":1, "toxic":2, "question":3, "Business":4, "SciTech":5, "Sports":6, "World":7}
```

But, in the `modeling_adapter.py` file, there are 20 task ids, the default setting.

```python
class MixAdapter(nn.Module):
    def __init__(self, config, bottleneck_size=100, adapter_num=20):
        super(MixAdapter, self).__init__()
        # 20 adapters with task_id 0--20, when task_id==-1 means dont use adapter
        self.mixadapter = nn.ModuleList([Adapter(config, bottleneck_size) for _ in range(adapter_num)])
        
    def forward(self, x, task_id=-1):
        if task_id==-1:
            return x
        else:
            return self.mixadapter[task_id](x)
```

Thus, I want to know the meaning of the remaining part (i.e., 12 task ids). Would you explain how to work? I may not be able to understand it properly.

Sincerely,
Young-Jun Lee

**Comment by andreamad8** [comment]
Hi, 

so because we thought to add some more skills later on. Those are empty adapters. 

So if you want you can set that variable to 8. It should work 👍 

Andrea
